/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetch } from "./client";
export interface CreateEventRequest {
  slug?: string;
  eventName?: string;
  description?: string;
  status?: string;
  createdBy?: string;
  venueId?: number;
  categoryIds?: number[];
  extraFeatureIds?: number[];
}

export interface EventResponse {
  eventId?: number;
  slug?: string;
  eventName?: string;
  description?: string;
  status?: string;
  createdBy?: string;
  venueId?: number;
  createdAt?: string;
  categoryIds?: number[];
  extraFeatureIds?: number[];
  venueName?: string;
  city?: string;
  categoryNames?: string[];
}

export interface CreateVenueRequest {
  name?: string;
  city?: string;
  country?: string;
}

export interface VenueResponse {
  id?: number;
  name?: string;
  city?: string;
  country?: string;
}

export interface CreateTicketListingRequest {
  eventId?: number;
  ticketType?: string;
  startDate?: string;
  endDate?: string;
  price?: number;
  currency?: string;
  ticketsAvailable?: number;
}

export interface TicketListingResponse {
  ticketListingId?: number;
  eventId?: number;
  companyId?: number;
  ticketType?: string;
  startDate?: string;
  endDate?: string;
  price?: number;
  currency?: string;
  ticketsAvailable?: number;
  createdAt?: string;
}

export interface CreateExtraFeatureRequest {
  name?: string;
}

export interface ExtraFeatureResponse {
  id?: number;
  name?: string;
}

export interface CreateFavoriteRequest {
  userId?: string;
  eventId?: number;
}

export interface CreateCategoryRequest {
  name?: string;
}

export interface CategoryResponse {
  id?: number;
  name?: string;
}

export interface FavoriteResponse {
  userId?: string;
  eventId?: number;
}

export type GetEventsParams = {
  city?: string;
  category?: string;
};

export type SearchByCityParams = {
  city: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getEventByIdResponse200 = {
  data: EventResponse;
  status: 200;
};

export type getEventByIdResponse400 = {
  data: string;
  status: 400;
};

export type getEventByIdResponse409 = {
  data: string;
  status: 409;
};

export type getEventByIdResponse500 = {
  data: string;
  status: 500;
};

export type getEventByIdResponseSuccess = getEventByIdResponse200 & {
  headers: Headers;
};
export type getEventByIdResponseError = (
  | getEventByIdResponse400
  | getEventByIdResponse409
  | getEventByIdResponse500
) & {
  headers: Headers;
};

export type getEventByIdResponse =
  | getEventByIdResponseSuccess
  | getEventByIdResponseError;

export const getGetEventByIdUrl = (id: number) => {
  return `/events/${id}`;
};

export const getEventById = async (
  id: number,
  options?: RequestInit,
): Promise<getEventByIdResponse> => {
  return customFetch<getEventByIdResponse>(getGetEventByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetEventByIdQueryKey = (id: number) => {
  return [`/events/${id}`] as const;
};

export const getGetEventByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getEventById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEventByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventById>>> = ({
    signal,
  }) => getEventById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getEventById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEventByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEventById>>
>;
export type GetEventByIdQueryError = string;

export function useGetEventById<
  TData = Awaited<ReturnType<typeof getEventById>>,
  TError = string,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEventById<
  TData = Awaited<ReturnType<typeof getEventById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventById>>,
          TError,
          Awaited<ReturnType<typeof getEventById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEventById<
  TData = Awaited<ReturnType<typeof getEventById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetEventById<
  TData = Awaited<ReturnType<typeof getEventById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetEventByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type updateEventResponse200 = {
  data: EventResponse;
  status: 200;
};

export type updateEventResponse400 = {
  data: string;
  status: 400;
};

export type updateEventResponse409 = {
  data: string;
  status: 409;
};

export type updateEventResponse500 = {
  data: string;
  status: 500;
};

export type updateEventResponseSuccess = updateEventResponse200 & {
  headers: Headers;
};
export type updateEventResponseError = (
  | updateEventResponse400
  | updateEventResponse409
  | updateEventResponse500
) & {
  headers: Headers;
};

export type updateEventResponse =
  | updateEventResponseSuccess
  | updateEventResponseError;

export const getUpdateEventUrl = (id: number) => {
  return `/events/${id}`;
};

export const updateEvent = async (
  id: number,
  createEventRequest: CreateEventRequest,
  options?: RequestInit,
): Promise<updateEventResponse> => {
  return customFetch<updateEventResponse>(getUpdateEventUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createEventRequest),
  });
};

export const getUpdateEventMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateEvent>>,
    TError,
    { id: number; data: CreateEventRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateEvent>>,
  TError,
  { id: number; data: CreateEventRequest },
  TContext
> => {
  const mutationKey = ["updateEvent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateEvent>>,
    { id: number; data: CreateEventRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateEvent(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateEvent>>
>;
export type UpdateEventMutationBody = CreateEventRequest;
export type UpdateEventMutationError = string;

export const useUpdateEvent = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateEvent>>,
      TError,
      { id: number; data: CreateEventRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateEvent>>,
  TError,
  { id: number; data: CreateEventRequest },
  TContext
> => {
  return useMutation(getUpdateEventMutationOptions(options), queryClient);
};

export type deleteEventResponse204 = {
  data: void;
  status: 204;
};

export type deleteEventResponse400 = {
  data: string;
  status: 400;
};

export type deleteEventResponse409 = {
  data: string;
  status: 409;
};

export type deleteEventResponse500 = {
  data: string;
  status: 500;
};

export type deleteEventResponseSuccess = deleteEventResponse204 & {
  headers: Headers;
};
export type deleteEventResponseError = (
  | deleteEventResponse400
  | deleteEventResponse409
  | deleteEventResponse500
) & {
  headers: Headers;
};

export type deleteEventResponse =
  | deleteEventResponseSuccess
  | deleteEventResponseError;

export const getDeleteEventUrl = (id: number) => {
  return `/events/${id}`;
};

export const deleteEvent = async (
  id: number,
  options?: RequestInit,
): Promise<deleteEventResponse> => {
  return customFetch<deleteEventResponse>(getDeleteEventUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteEventMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteEvent>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteEvent>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteEvent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteEvent>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteEvent(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteEvent>>
>;

export type DeleteEventMutationError = string;

export const useDeleteEvent = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteEvent>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteEvent>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteEventMutationOptions(options), queryClient);
};

export type getAllResponse200 = {
  data: VenueResponse[];
  status: 200;
};

export type getAllResponse400 = {
  data: string;
  status: 400;
};

export type getAllResponse409 = {
  data: string;
  status: 409;
};

export type getAllResponse500 = {
  data: string;
  status: 500;
};

export type getAllResponseSuccess = getAllResponse200 & {
  headers: Headers;
};
export type getAllResponseError = (
  | getAllResponse400
  | getAllResponse409
  | getAllResponse500
) & {
  headers: Headers;
};

export type getAllResponse = getAllResponseSuccess | getAllResponseError;

export const getGetAllUrl = () => {
  return `/venues`;
};

export const getAll = async (
  options?: RequestInit,
): Promise<getAllResponse> => {
  return customFetch<getAllResponse>(getGetAllUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAllQueryKey = () => {
  return [`/venues`] as const;
};

export const getGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = string,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAll>>> = ({
    signal,
  }) => getAll({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllQueryResult = NonNullable<Awaited<ReturnType<typeof getAll>>>;
export type GetAllQueryError = string;

export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = string,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll>>,
          TError,
          Awaited<ReturnType<typeof getAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAll<
  TData = Awaited<ReturnType<typeof getAll>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type createResponse201 = {
  data: VenueResponse;
  status: 201;
};

export type createResponse400 = {
  data: string;
  status: 400;
};

export type createResponse409 = {
  data: string;
  status: 409;
};

export type createResponse500 = {
  data: string;
  status: 500;
};

export type createResponseSuccess = createResponse201 & {
  headers: Headers;
};
export type createResponseError = (
  | createResponse400
  | createResponse409
  | createResponse500
) & {
  headers: Headers;
};

export type createResponse = createResponseSuccess | createResponseError;

export const getCreateUrl = () => {
  return `/venues`;
};

export const create = async (
  createVenueRequest: CreateVenueRequest,
  options?: RequestInit,
): Promise<createResponse> => {
  return customFetch<createResponse>(getCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createVenueRequest),
  });
};

export const getCreateMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create>>,
    TError,
    { data: CreateVenueRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: CreateVenueRequest },
  TContext
> => {
  const mutationKey = ["create"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create>>,
    { data: CreateVenueRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof create>>
>;
export type CreateMutationBody = CreateVenueRequest;
export type CreateMutationError = string;

export const useCreate = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create>>,
      TError,
      { data: CreateVenueRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: CreateVenueRequest },
  TContext
> => {
  return useMutation(getCreateMutationOptions(options), queryClient);
};

export type createTicketListingResponse201 = {
  data: TicketListingResponse;
  status: 201;
};

export type createTicketListingResponse400 = {
  data: string;
  status: 400;
};

export type createTicketListingResponse409 = {
  data: string;
  status: 409;
};

export type createTicketListingResponse500 = {
  data: string;
  status: 500;
};

export type createTicketListingResponseSuccess =
  createTicketListingResponse201 & {
    headers: Headers;
  };
export type createTicketListingResponseError = (
  | createTicketListingResponse400
  | createTicketListingResponse409
  | createTicketListingResponse500
) & {
  headers: Headers;
};

export type createTicketListingResponse =
  | createTicketListingResponseSuccess
  | createTicketListingResponseError;

export const getCreateTicketListingUrl = () => {
  return `/ticket-listings`;
};

export const createTicketListing = async (
  createTicketListingRequest: CreateTicketListingRequest,
  options?: RequestInit,
): Promise<createTicketListingResponse> => {
  return customFetch<createTicketListingResponse>(getCreateTicketListingUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createTicketListingRequest),
  });
};

export const getCreateTicketListingMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTicketListing>>,
    TError,
    { data: CreateTicketListingRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTicketListing>>,
  TError,
  { data: CreateTicketListingRequest },
  TContext
> => {
  const mutationKey = ["createTicketListing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTicketListing>>,
    { data: CreateTicketListingRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createTicketListing(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTicketListingMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTicketListing>>
>;
export type CreateTicketListingMutationBody = CreateTicketListingRequest;
export type CreateTicketListingMutationError = string;

export const useCreateTicketListing = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTicketListing>>,
      TError,
      { data: CreateTicketListingRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createTicketListing>>,
  TError,
  { data: CreateTicketListingRequest },
  TContext
> => {
  return useMutation(
    getCreateTicketListingMutationOptions(options),
    queryClient,
  );
};

export type getAll1Response200 = {
  data: ExtraFeatureResponse[];
  status: 200;
};

export type getAll1Response400 = {
  data: string;
  status: 400;
};

export type getAll1Response409 = {
  data: string;
  status: 409;
};

export type getAll1Response500 = {
  data: string;
  status: 500;
};

export type getAll1ResponseSuccess = getAll1Response200 & {
  headers: Headers;
};
export type getAll1ResponseError = (
  | getAll1Response400
  | getAll1Response409
  | getAll1Response500
) & {
  headers: Headers;
};

export type getAll1Response = getAll1ResponseSuccess | getAll1ResponseError;

export const getGetAll1Url = () => {
  return `/features`;
};

export const getAll1 = async (
  options?: RequestInit,
): Promise<getAll1Response> => {
  return customFetch<getAll1Response>(getGetAll1Url(), {
    ...options,
    method: "GET",
  });
};

export const getGetAll1QueryKey = () => {
  return [`/features`] as const;
};

export const getGetAll1QueryOptions = <
  TData = Awaited<ReturnType<typeof getAll1>>,
  TError = string,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAll1>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAll1QueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAll1>>> = ({
    signal,
  }) => getAll1({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAll1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAll1QueryResult = NonNullable<
  Awaited<ReturnType<typeof getAll1>>
>;
export type GetAll1QueryError = string;

export function useGetAll1<
  TData = Awaited<ReturnType<typeof getAll1>>,
  TError = string,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll1>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll1>>,
          TError,
          Awaited<ReturnType<typeof getAll1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll1<
  TData = Awaited<ReturnType<typeof getAll1>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll1>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAll1>>,
          TError,
          Awaited<ReturnType<typeof getAll1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAll1<
  TData = Awaited<ReturnType<typeof getAll1>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAll1<
  TData = Awaited<ReturnType<typeof getAll1>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAll1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAll1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type create1Response201 = {
  data: ExtraFeatureResponse;
  status: 201;
};

export type create1Response400 = {
  data: string;
  status: 400;
};

export type create1Response409 = {
  data: string;
  status: 409;
};

export type create1Response500 = {
  data: string;
  status: 500;
};

export type create1ResponseSuccess = create1Response201 & {
  headers: Headers;
};
export type create1ResponseError = (
  | create1Response400
  | create1Response409
  | create1Response500
) & {
  headers: Headers;
};

export type create1Response = create1ResponseSuccess | create1ResponseError;

export const getCreate1Url = () => {
  return `/features`;
};

export const create1 = async (
  createExtraFeatureRequest: CreateExtraFeatureRequest,
  options?: RequestInit,
): Promise<create1Response> => {
  return customFetch<create1Response>(getCreate1Url(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createExtraFeatureRequest),
  });
};

export const getCreate1MutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create1>>,
    TError,
    { data: CreateExtraFeatureRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: CreateExtraFeatureRequest },
  TContext
> => {
  const mutationKey = ["create1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create1>>,
    { data: CreateExtraFeatureRequest }
  > = (props) => {
    const { data } = props ?? {};

    return create1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Create1MutationResult = NonNullable<
  Awaited<ReturnType<typeof create1>>
>;
export type Create1MutationBody = CreateExtraFeatureRequest;
export type Create1MutationError = string;

export const useCreate1 = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create1>>,
      TError,
      { data: CreateExtraFeatureRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { data: CreateExtraFeatureRequest },
  TContext
> => {
  return useMutation(getCreate1MutationOptions(options), queryClient);
};

export type addToEventResponse200 = {
  data: string;
  status: 200;
};

export type addToEventResponse400 = {
  data: string;
  status: 400;
};

export type addToEventResponse409 = {
  data: string;
  status: 409;
};

export type addToEventResponse500 = {
  data: string;
  status: 500;
};

export type addToEventResponseSuccess = addToEventResponse200 & {
  headers: Headers;
};
export type addToEventResponseError = (
  | addToEventResponse400
  | addToEventResponse409
  | addToEventResponse500
) & {
  headers: Headers;
};

export type addToEventResponse =
  | addToEventResponseSuccess
  | addToEventResponseError;

export const getAddToEventUrl = (featureId: number, eventId: number) => {
  return `/features/${featureId}/events/${eventId}`;
};

export const addToEvent = async (
  featureId: number,
  eventId: number,
  options?: RequestInit,
): Promise<addToEventResponse> => {
  return customFetch<addToEventResponse>(getAddToEventUrl(featureId, eventId), {
    ...options,
    method: "POST",
  });
};

export const getAddToEventMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addToEvent>>,
    TError,
    { featureId: number; eventId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addToEvent>>,
  TError,
  { featureId: number; eventId: number },
  TContext
> => {
  const mutationKey = ["addToEvent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addToEvent>>,
    { featureId: number; eventId: number }
  > = (props) => {
    const { featureId, eventId } = props ?? {};

    return addToEvent(featureId, eventId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddToEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof addToEvent>>
>;

export type AddToEventMutationError = string;

export const useAddToEvent = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addToEvent>>,
      TError,
      { featureId: number; eventId: number },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addToEvent>>,
  TError,
  { featureId: number; eventId: number },
  TContext
> => {
  return useMutation(getAddToEventMutationOptions(options), queryClient);
};

export type getFavoritesResponse200 = {
  data: FavoriteResponse[];
  status: 200;
};

export type getFavoritesResponse400 = {
  data: string;
  status: 400;
};

export type getFavoritesResponse409 = {
  data: string;
  status: 409;
};

export type getFavoritesResponse500 = {
  data: string;
  status: 500;
};

export type getFavoritesResponseSuccess = getFavoritesResponse200 & {
  headers: Headers;
};
export type getFavoritesResponseError = (
  | getFavoritesResponse400
  | getFavoritesResponse409
  | getFavoritesResponse500
) & {
  headers: Headers;
};

export type getFavoritesResponse =
  | getFavoritesResponseSuccess
  | getFavoritesResponseError;

export const getGetFavoritesUrl = () => {
  return `/favorites`;
};

export const getFavorites = async (
  options?: RequestInit,
): Promise<getFavoritesResponse> => {
  return customFetch<getFavoritesResponse>(getGetFavoritesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetFavoritesQueryKey = () => {
  return [`/favorites`] as const;
};

export const getGetFavoritesQueryOptions = <
  TData = Awaited<ReturnType<typeof getFavorites>>,
  TError = string,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFavoritesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFavorites>>> = ({
    signal,
  }) => getFavorites({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFavorites>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFavoritesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFavorites>>
>;
export type GetFavoritesQueryError = string;

export function useGetFavorites<
  TData = Awaited<ReturnType<typeof getFavorites>>,
  TError = string,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavorites>>,
          TError,
          Awaited<ReturnType<typeof getFavorites>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFavorites<
  TData = Awaited<ReturnType<typeof getFavorites>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavorites>>,
          TError,
          Awaited<ReturnType<typeof getFavorites>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFavorites<
  TData = Awaited<ReturnType<typeof getFavorites>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetFavorites<
  TData = Awaited<ReturnType<typeof getFavorites>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFavoritesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type addFavoriteResponse201 = {
  data: void;
  status: 201;
};

export type addFavoriteResponse400 = {
  data: string;
  status: 400;
};

export type addFavoriteResponse409 = {
  data: string;
  status: 409;
};

export type addFavoriteResponse500 = {
  data: string;
  status: 500;
};

export type addFavoriteResponseSuccess = addFavoriteResponse201 & {
  headers: Headers;
};
export type addFavoriteResponseError = (
  | addFavoriteResponse400
  | addFavoriteResponse409
  | addFavoriteResponse500
) & {
  headers: Headers;
};

export type addFavoriteResponse =
  | addFavoriteResponseSuccess
  | addFavoriteResponseError;

export const getAddFavoriteUrl = () => {
  return `/favorites`;
};

export const addFavorite = async (
  createFavoriteRequest: CreateFavoriteRequest,
  options?: RequestInit,
): Promise<addFavoriteResponse> => {
  return customFetch<addFavoriteResponse>(getAddFavoriteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createFavoriteRequest),
  });
};

export const getAddFavoriteMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addFavorite>>,
    TError,
    { data: CreateFavoriteRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addFavorite>>,
  TError,
  { data: CreateFavoriteRequest },
  TContext
> => {
  const mutationKey = ["addFavorite"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addFavorite>>,
    { data: CreateFavoriteRequest }
  > = (props) => {
    const { data } = props ?? {};

    return addFavorite(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddFavoriteMutationResult = NonNullable<
  Awaited<ReturnType<typeof addFavorite>>
>;
export type AddFavoriteMutationBody = CreateFavoriteRequest;
export type AddFavoriteMutationError = string;

export const useAddFavorite = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addFavorite>>,
      TError,
      { data: CreateFavoriteRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addFavorite>>,
  TError,
  { data: CreateFavoriteRequest },
  TContext
> => {
  return useMutation(getAddFavoriteMutationOptions(options), queryClient);
};

export type getEventsResponse200 = {
  data: EventResponse[];
  status: 200;
};

export type getEventsResponse400 = {
  data: string;
  status: 400;
};

export type getEventsResponse409 = {
  data: string;
  status: 409;
};

export type getEventsResponse500 = {
  data: string;
  status: 500;
};

export type getEventsResponseSuccess = getEventsResponse200 & {
  headers: Headers;
};
export type getEventsResponseError = (
  | getEventsResponse400
  | getEventsResponse409
  | getEventsResponse500
) & {
  headers: Headers;
};

export type getEventsResponse =
  | getEventsResponseSuccess
  | getEventsResponseError;

export const getGetEventsUrl = (params?: GetEventsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/events?${stringifiedParams}`
    : `/events`;
};

/**
 * @summary Get all events
 */
export const getEvents = async (
  params?: GetEventsParams,
  options?: RequestInit,
): Promise<getEventsResponse> => {
  return customFetch<getEventsResponse>(getGetEventsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetEventsQueryKey = (params?: GetEventsParams) => {
  return [`/events`, ...(params ? [params] : [])] as const;
};

export const getGetEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof getEvents>>,
  TError = string,
>(
  params?: GetEventsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEventsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEvents>>> = ({
    signal,
  }) => getEvents(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEvents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEvents>>
>;
export type GetEventsQueryError = string;

export function useGetEvents<
  TData = Awaited<ReturnType<typeof getEvents>>,
  TError = string,
>(
  params: undefined | GetEventsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvents>>,
          TError,
          Awaited<ReturnType<typeof getEvents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEvents<
  TData = Awaited<ReturnType<typeof getEvents>>,
  TError = string,
>(
  params?: GetEventsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvents>>,
          TError,
          Awaited<ReturnType<typeof getEvents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEvents<
  TData = Awaited<ReturnType<typeof getEvents>>,
  TError = string,
>(
  params?: GetEventsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all events
 */

export function useGetEvents<
  TData = Awaited<ReturnType<typeof getEvents>>,
  TError = string,
>(
  params?: GetEventsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetEventsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type createEventResponse201 = {
  data: EventResponse;
  status: 201;
};

export type createEventResponse400 = {
  data: string;
  status: 400;
};

export type createEventResponse409 = {
  data: string;
  status: 409;
};

export type createEventResponse500 = {
  data: string;
  status: 500;
};

export type createEventResponseSuccess = createEventResponse201 & {
  headers: Headers;
};
export type createEventResponseError = (
  | createEventResponse400
  | createEventResponse409
  | createEventResponse500
) & {
  headers: Headers;
};

export type createEventResponse =
  | createEventResponseSuccess
  | createEventResponseError;

export const getCreateEventUrl = () => {
  return `/events`;
};

export const createEvent = async (
  createEventRequest: CreateEventRequest,
  options?: RequestInit,
): Promise<createEventResponse> => {
  return customFetch<createEventResponse>(getCreateEventUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createEventRequest),
  });
};

export const getCreateEventMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createEvent>>,
    TError,
    { data: CreateEventRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createEvent>>,
  TError,
  { data: CreateEventRequest },
  TContext
> => {
  const mutationKey = ["createEvent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createEvent>>,
    { data: CreateEventRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createEvent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof createEvent>>
>;
export type CreateEventMutationBody = CreateEventRequest;
export type CreateEventMutationError = string;

export const useCreateEvent = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createEvent>>,
      TError,
      { data: CreateEventRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createEvent>>,
  TError,
  { data: CreateEventRequest },
  TContext
> => {
  return useMutation(getCreateEventMutationOptions(options), queryClient);
};

export type getAllCategoriesResponse200 = {
  data: CategoryResponse[];
  status: 200;
};

export type getAllCategoriesResponse400 = {
  data: string;
  status: 400;
};

export type getAllCategoriesResponse409 = {
  data: string;
  status: 409;
};

export type getAllCategoriesResponse500 = {
  data: string;
  status: 500;
};

export type getAllCategoriesResponseSuccess = getAllCategoriesResponse200 & {
  headers: Headers;
};
export type getAllCategoriesResponseError = (
  | getAllCategoriesResponse400
  | getAllCategoriesResponse409
  | getAllCategoriesResponse500
) & {
  headers: Headers;
};

export type getAllCategoriesResponse =
  | getAllCategoriesResponseSuccess
  | getAllCategoriesResponseError;

export const getGetAllCategoriesUrl = () => {
  return `/categories`;
};

export const getAllCategories = async (
  options?: RequestInit,
): Promise<getAllCategoriesResponse> => {
  return customFetch<getAllCategoriesResponse>(getGetAllCategoriesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAllCategoriesQueryKey = () => {
  return [`/categories`] as const;
};

export const getGetAllCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = string,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllCategories>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllCategoriesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllCategories>>
  > = ({ signal }) => getAllCategories({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllCategories>>
>;
export type GetAllCategoriesQueryError = string;

export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = string,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllCategories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllCategories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllCategoriesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type createCategoryResponse201 = {
  data: CategoryResponse;
  status: 201;
};

export type createCategoryResponse400 = {
  data: string;
  status: 400;
};

export type createCategoryResponse409 = {
  data: string;
  status: 409;
};

export type createCategoryResponse500 = {
  data: string;
  status: 500;
};

export type createCategoryResponseSuccess = createCategoryResponse201 & {
  headers: Headers;
};
export type createCategoryResponseError = (
  | createCategoryResponse400
  | createCategoryResponse409
  | createCategoryResponse500
) & {
  headers: Headers;
};

export type createCategoryResponse =
  | createCategoryResponseSuccess
  | createCategoryResponseError;

export const getCreateCategoryUrl = () => {
  return `/categories`;
};

export const createCategory = async (
  createCategoryRequest: CreateCategoryRequest,
  options?: RequestInit,
): Promise<createCategoryResponse> => {
  return customFetch<createCategoryResponse>(getCreateCategoryUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCategoryRequest),
  });
};

export const getCreateCategoryMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCategory>>,
    TError,
    { data: CreateCategoryRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: CreateCategoryRequest },
  TContext
> => {
  const mutationKey = ["createCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCategory>>,
    { data: CreateCategoryRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createCategory(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCategory>>
>;
export type CreateCategoryMutationBody = CreateCategoryRequest;
export type CreateCategoryMutationError = string;

export const useCreateCategory = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCategory>>,
      TError,
      { data: CreateCategoryRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: CreateCategoryRequest },
  TContext
> => {
  return useMutation(getCreateCategoryMutationOptions(options), queryClient);
};

export type getByIdResponse200 = {
  data: VenueResponse;
  status: 200;
};

export type getByIdResponse400 = {
  data: string;
  status: 400;
};

export type getByIdResponse409 = {
  data: string;
  status: 409;
};

export type getByIdResponse500 = {
  data: string;
  status: 500;
};

export type getByIdResponseSuccess = getByIdResponse200 & {
  headers: Headers;
};
export type getByIdResponseError = (
  | getByIdResponse400
  | getByIdResponse409
  | getByIdResponse500
) & {
  headers: Headers;
};

export type getByIdResponse = getByIdResponseSuccess | getByIdResponseError;

export const getGetByIdUrl = (id: number) => {
  return `/venues/${id}`;
};

export const getById = async (
  id: number,
  options?: RequestInit,
): Promise<getByIdResponse> => {
  return customFetch<getByIdResponse>(getGetByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetByIdQueryKey = (id: number) => {
  return [`/venues/${id}`] as const;
};

export const getGetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getById>>> = ({
    signal,
  }) => getById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getById>>
>;
export type GetByIdQueryError = string;

export function useGetById<
  TData = Awaited<ReturnType<typeof getById>>,
  TError = string,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById>>,
          TError,
          Awaited<ReturnType<typeof getById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetById<
  TData = Awaited<ReturnType<typeof getById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById>>,
          TError,
          Awaited<ReturnType<typeof getById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetById<
  TData = Awaited<ReturnType<typeof getById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetById<
  TData = Awaited<ReturnType<typeof getById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type _deleteResponse204 = {
  data: void;
  status: 204;
};

export type _deleteResponse400 = {
  data: string;
  status: 400;
};

export type _deleteResponse409 = {
  data: string;
  status: 409;
};

export type _deleteResponse500 = {
  data: string;
  status: 500;
};

export type _deleteResponseSuccess = _deleteResponse204 & {
  headers: Headers;
};
export type _deleteResponseError = (
  | _deleteResponse400
  | _deleteResponse409
  | _deleteResponse500
) & {
  headers: Headers;
};

export type _deleteResponse = _deleteResponseSuccess | _deleteResponseError;

export const getDeleteUrl = (id: number) => {
  return `/venues/${id}`;
};

export const _delete = async (
  id: number,
  options?: RequestInit,
): Promise<_deleteResponse> => {
  return customFetch<_deleteResponse>(getDeleteUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof _delete>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["_delete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof _delete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return _delete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type _DeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof _delete>>
>;

export type _DeleteMutationError = string;

export const useDelete = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof _delete>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof _delete>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteMutationOptions(options), queryClient);
};

export type searchByCityResponse200 = {
  data: VenueResponse[];
  status: 200;
};

export type searchByCityResponse400 = {
  data: string;
  status: 400;
};

export type searchByCityResponse409 = {
  data: string;
  status: 409;
};

export type searchByCityResponse500 = {
  data: string;
  status: 500;
};

export type searchByCityResponseSuccess = searchByCityResponse200 & {
  headers: Headers;
};
export type searchByCityResponseError = (
  | searchByCityResponse400
  | searchByCityResponse409
  | searchByCityResponse500
) & {
  headers: Headers;
};

export type searchByCityResponse =
  | searchByCityResponseSuccess
  | searchByCityResponseError;

export const getSearchByCityUrl = (params: SearchByCityParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/venues/search?${stringifiedParams}`
    : `/venues/search`;
};

export const searchByCity = async (
  params: SearchByCityParams,
  options?: RequestInit,
): Promise<searchByCityResponse> => {
  return customFetch<searchByCityResponse>(getSearchByCityUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getSearchByCityQueryKey = (params?: SearchByCityParams) => {
  return [`/venues/search`, ...(params ? [params] : [])] as const;
};

export const getSearchByCityQueryOptions = <
  TData = Awaited<ReturnType<typeof searchByCity>>,
  TError = string,
>(
  params: SearchByCityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchByCity>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchByCityQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchByCity>>> = ({
    signal,
  }) => searchByCity(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchByCity>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchByCityQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchByCity>>
>;
export type SearchByCityQueryError = string;

export function useSearchByCity<
  TData = Awaited<ReturnType<typeof searchByCity>>,
  TError = string,
>(
  params: SearchByCityParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchByCity>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByCity>>,
          TError,
          Awaited<ReturnType<typeof searchByCity>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchByCity<
  TData = Awaited<ReturnType<typeof searchByCity>>,
  TError = string,
>(
  params: SearchByCityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchByCity>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByCity>>,
          TError,
          Awaited<ReturnType<typeof searchByCity>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchByCity<
  TData = Awaited<ReturnType<typeof searchByCity>>,
  TError = string,
>(
  params: SearchByCityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchByCity>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSearchByCity<
  TData = Awaited<ReturnType<typeof searchByCity>>,
  TError = string,
>(
  params: SearchByCityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchByCity>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchByCityQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getListingsByEventResponse200 = {
  data: TicketListingResponse[];
  status: 200;
};

export type getListingsByEventResponse400 = {
  data: string;
  status: 400;
};

export type getListingsByEventResponse409 = {
  data: string;
  status: 409;
};

export type getListingsByEventResponse500 = {
  data: string;
  status: 500;
};

export type getListingsByEventResponseSuccess =
  getListingsByEventResponse200 & {
    headers: Headers;
  };
export type getListingsByEventResponseError = (
  | getListingsByEventResponse400
  | getListingsByEventResponse409
  | getListingsByEventResponse500
) & {
  headers: Headers;
};

export type getListingsByEventResponse =
  | getListingsByEventResponseSuccess
  | getListingsByEventResponseError;

export const getGetListingsByEventUrl = (eventId: number) => {
  return `/ticket-listings/event/${eventId}`;
};

export const getListingsByEvent = async (
  eventId: number,
  options?: RequestInit,
): Promise<getListingsByEventResponse> => {
  return customFetch<getListingsByEventResponse>(
    getGetListingsByEventUrl(eventId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetListingsByEventQueryKey = (eventId: number) => {
  return [`/ticket-listings/event/${eventId}`] as const;
};

export const getGetListingsByEventQueryOptions = <
  TData = Awaited<ReturnType<typeof getListingsByEvent>>,
  TError = string,
>(
  eventId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListingsByEvent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetListingsByEventQueryKey(eventId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getListingsByEvent>>
  > = ({ signal }) =>
    getListingsByEvent(eventId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!eventId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getListingsByEvent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetListingsByEventQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListingsByEvent>>
>;
export type GetListingsByEventQueryError = string;

export function useGetListingsByEvent<
  TData = Awaited<ReturnType<typeof getListingsByEvent>>,
  TError = string,
>(
  eventId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListingsByEvent>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListingsByEvent>>,
          TError,
          Awaited<ReturnType<typeof getListingsByEvent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetListingsByEvent<
  TData = Awaited<ReturnType<typeof getListingsByEvent>>,
  TError = string,
>(
  eventId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListingsByEvent>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListingsByEvent>>,
          TError,
          Awaited<ReturnType<typeof getListingsByEvent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetListingsByEvent<
  TData = Awaited<ReturnType<typeof getListingsByEvent>>,
  TError = string,
>(
  eventId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListingsByEvent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetListingsByEvent<
  TData = Awaited<ReturnType<typeof getListingsByEvent>>,
  TError = string,
>(
  eventId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getListingsByEvent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetListingsByEventQueryOptions(eventId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type homeResponse200 = {
  data: string;
  status: 200;
};

export type homeResponse400 = {
  data: string;
  status: 400;
};

export type homeResponse409 = {
  data: string;
  status: 409;
};

export type homeResponse500 = {
  data: string;
  status: 500;
};

export type homeResponseSuccess = homeResponse200 & {
  headers: Headers;
};
export type homeResponseError = (
  | homeResponse400
  | homeResponse409
  | homeResponse500
) & {
  headers: Headers;
};

export type homeResponse = homeResponseSuccess | homeResponseError;

export const getHomeUrl = () => {
  return `/ho`;
};

export const home = async (options?: RequestInit): Promise<homeResponse> => {
  return customFetch<homeResponse>(getHomeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHomeQueryKey = () => {
  return [`/ho`] as const;
};

export const getHomeQueryOptions = <
  TData = Awaited<ReturnType<typeof home>>,
  TError = string,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHomeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof home>>> = ({
    signal,
  }) => home({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof home>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HomeQueryResult = NonNullable<Awaited<ReturnType<typeof home>>>;
export type HomeQueryError = string;

export function useHome<
  TData = Awaited<ReturnType<typeof home>>,
  TError = string,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof home>>,
          TError,
          Awaited<ReturnType<typeof home>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHome<
  TData = Awaited<ReturnType<typeof home>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof home>>,
          TError,
          Awaited<ReturnType<typeof home>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHome<
  TData = Awaited<ReturnType<typeof home>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHome<
  TData = Awaited<ReturnType<typeof home>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof home>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHomeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getById1Response200 = {
  data: ExtraFeatureResponse;
  status: 200;
};

export type getById1Response400 = {
  data: string;
  status: 400;
};

export type getById1Response409 = {
  data: string;
  status: 409;
};

export type getById1Response500 = {
  data: string;
  status: 500;
};

export type getById1ResponseSuccess = getById1Response200 & {
  headers: Headers;
};
export type getById1ResponseError = (
  | getById1Response400
  | getById1Response409
  | getById1Response500
) & {
  headers: Headers;
};

export type getById1Response = getById1ResponseSuccess | getById1ResponseError;

export const getGetById1Url = (id: number) => {
  return `/features/${id}`;
};

export const getById1 = async (
  id: number,
  options?: RequestInit,
): Promise<getById1Response> => {
  return customFetch<getById1Response>(getGetById1Url(id), {
    ...options,
    method: "GET",
  });
};

export const getGetById1QueryKey = (id: number) => {
  return [`/features/${id}`] as const;
};

export const getGetById1QueryOptions = <
  TData = Awaited<ReturnType<typeof getById1>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetById1QueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getById1>>> = ({
    signal,
  }) => getById1(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getById1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetById1QueryResult = NonNullable<
  Awaited<ReturnType<typeof getById1>>
>;
export type GetById1QueryError = string;

export function useGetById1<
  TData = Awaited<ReturnType<typeof getById1>>,
  TError = string,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById1>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById1>>,
          TError,
          Awaited<ReturnType<typeof getById1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetById1<
  TData = Awaited<ReturnType<typeof getById1>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById1>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById1>>,
          TError,
          Awaited<ReturnType<typeof getById1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetById1<
  TData = Awaited<ReturnType<typeof getById1>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetById1<
  TData = Awaited<ReturnType<typeof getById1>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById1>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetById1QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type delete1Response204 = {
  data: void;
  status: 204;
};

export type delete1Response400 = {
  data: string;
  status: 400;
};

export type delete1Response409 = {
  data: string;
  status: 409;
};

export type delete1Response500 = {
  data: string;
  status: 500;
};

export type delete1ResponseSuccess = delete1Response204 & {
  headers: Headers;
};
export type delete1ResponseError = (
  | delete1Response400
  | delete1Response409
  | delete1Response500
) & {
  headers: Headers;
};

export type delete1Response = delete1ResponseSuccess | delete1ResponseError;

export const getDelete1Url = (id: number) => {
  return `/features/${id}`;
};

export const delete1 = async (
  id: number,
  options?: RequestInit,
): Promise<delete1Response> => {
  return customFetch<delete1Response>(getDelete1Url(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDelete1MutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof delete1>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof delete1>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["delete1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof delete1>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return delete1(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Delete1MutationResult = NonNullable<
  Awaited<ReturnType<typeof delete1>>
>;

export type Delete1MutationError = string;

export const useDelete1 = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof delete1>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof delete1>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDelete1MutationOptions(options), queryClient);
};

export type getEventBySlugResponse200 = {
  data: EventResponse;
  status: 200;
};

export type getEventBySlugResponse400 = {
  data: string;
  status: 400;
};

export type getEventBySlugResponse409 = {
  data: string;
  status: 409;
};

export type getEventBySlugResponse500 = {
  data: string;
  status: 500;
};

export type getEventBySlugResponseSuccess = getEventBySlugResponse200 & {
  headers: Headers;
};
export type getEventBySlugResponseError = (
  | getEventBySlugResponse400
  | getEventBySlugResponse409
  | getEventBySlugResponse500
) & {
  headers: Headers;
};

export type getEventBySlugResponse =
  | getEventBySlugResponseSuccess
  | getEventBySlugResponseError;

export const getGetEventBySlugUrl = (slug: string) => {
  return `/events/slug/${slug}`;
};

export const getEventBySlug = async (
  slug: string,
  options?: RequestInit,
): Promise<getEventBySlugResponse> => {
  return customFetch<getEventBySlugResponse>(getGetEventBySlugUrl(slug), {
    ...options,
    method: "GET",
  });
};

export const getGetEventBySlugQueryKey = (slug: string) => {
  return [`/events/slug/${slug}`] as const;
};

export const getGetEventBySlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getEventBySlug>>,
  TError = string,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventBySlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEventBySlugQueryKey(slug);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventBySlug>>> = ({
    signal,
  }) => getEventBySlug(slug, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getEventBySlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEventBySlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEventBySlug>>
>;
export type GetEventBySlugQueryError = string;

export function useGetEventBySlug<
  TData = Awaited<ReturnType<typeof getEventBySlug>>,
  TError = string,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventBySlug>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventBySlug>>,
          TError,
          Awaited<ReturnType<typeof getEventBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEventBySlug<
  TData = Awaited<ReturnType<typeof getEventBySlug>>,
  TError = string,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventBySlug>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventBySlug>>,
          TError,
          Awaited<ReturnType<typeof getEventBySlug>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEventBySlug<
  TData = Awaited<ReturnType<typeof getEventBySlug>>,
  TError = string,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventBySlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetEventBySlug<
  TData = Awaited<ReturnType<typeof getEventBySlug>>,
  TError = string,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEventBySlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetEventBySlugQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getCategoryByIdResponse200 = {
  data: CategoryResponse;
  status: 200;
};

export type getCategoryByIdResponse400 = {
  data: string;
  status: 400;
};

export type getCategoryByIdResponse409 = {
  data: string;
  status: 409;
};

export type getCategoryByIdResponse500 = {
  data: string;
  status: 500;
};

export type getCategoryByIdResponseSuccess = getCategoryByIdResponse200 & {
  headers: Headers;
};
export type getCategoryByIdResponseError = (
  | getCategoryByIdResponse400
  | getCategoryByIdResponse409
  | getCategoryByIdResponse500
) & {
  headers: Headers;
};

export type getCategoryByIdResponse =
  | getCategoryByIdResponseSuccess
  | getCategoryByIdResponseError;

export const getGetCategoryByIdUrl = (id: number) => {
  return `/categories/${id}`;
};

export const getCategoryById = async (
  id: number,
  options?: RequestInit,
): Promise<getCategoryByIdResponse> => {
  return customFetch<getCategoryByIdResponse>(getGetCategoryByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetCategoryByIdQueryKey = (id: number) => {
  return [`/categories/${id}`] as const;
};

export const getGetCategoryByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCategoryById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoryById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCategoryByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategoryById>>> = ({
    signal,
  }) => getCategoryById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCategoryById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCategoryByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCategoryById>>
>;
export type GetCategoryByIdQueryError = string;

export function useGetCategoryById<
  TData = Awaited<ReturnType<typeof getCategoryById>>,
  TError = string,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoryById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoryById>>,
          TError,
          Awaited<ReturnType<typeof getCategoryById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCategoryById<
  TData = Awaited<ReturnType<typeof getCategoryById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoryById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategoryById>>,
          TError,
          Awaited<ReturnType<typeof getCategoryById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCategoryById<
  TData = Awaited<ReturnType<typeof getCategoryById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoryById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCategoryById<
  TData = Awaited<ReturnType<typeof getCategoryById>>,
  TError = string,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCategoryById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCategoryByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type deleteCategoryResponse204 = {
  data: void;
  status: 204;
};

export type deleteCategoryResponse400 = {
  data: string;
  status: 400;
};

export type deleteCategoryResponse409 = {
  data: string;
  status: 409;
};

export type deleteCategoryResponse500 = {
  data: string;
  status: 500;
};

export type deleteCategoryResponseSuccess = deleteCategoryResponse204 & {
  headers: Headers;
};
export type deleteCategoryResponseError = (
  | deleteCategoryResponse400
  | deleteCategoryResponse409
  | deleteCategoryResponse500
) & {
  headers: Headers;
};

export type deleteCategoryResponse =
  | deleteCategoryResponseSuccess
  | deleteCategoryResponseError;

export const getDeleteCategoryUrl = (id: number) => {
  return `/categories/${id}`;
};

export const deleteCategory = async (
  id: number,
  options?: RequestInit,
): Promise<deleteCategoryResponse> => {
  return customFetch<deleteCategoryResponse>(getDeleteCategoryUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteCategoryMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCategory>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCategory>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCategory(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCategory>>
>;

export type DeleteCategoryMutationError = string;

export const useDeleteCategory = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCategory>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteCategoryMutationOptions(options), queryClient);
};

export type deleteTicketListingResponse204 = {
  data: void;
  status: 204;
};

export type deleteTicketListingResponse400 = {
  data: string;
  status: 400;
};

export type deleteTicketListingResponse409 = {
  data: string;
  status: 409;
};

export type deleteTicketListingResponse500 = {
  data: string;
  status: 500;
};

export type deleteTicketListingResponseSuccess =
  deleteTicketListingResponse204 & {
    headers: Headers;
  };
export type deleteTicketListingResponseError = (
  | deleteTicketListingResponse400
  | deleteTicketListingResponse409
  | deleteTicketListingResponse500
) & {
  headers: Headers;
};

export type deleteTicketListingResponse =
  | deleteTicketListingResponseSuccess
  | deleteTicketListingResponseError;

export const getDeleteTicketListingUrl = (id: number) => {
  return `/ticket-listings/${id}`;
};

export const deleteTicketListing = async (
  id: number,
  options?: RequestInit,
): Promise<deleteTicketListingResponse> => {
  return customFetch<deleteTicketListingResponse>(
    getDeleteTicketListingUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteTicketListingMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTicketListing>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTicketListing>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteTicketListing"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTicketListing>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteTicketListing(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTicketListingMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTicketListing>>
>;

export type DeleteTicketListingMutationError = string;

export const useDeleteTicketListing = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTicketListing>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTicketListing>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getDeleteTicketListingMutationOptions(options),
    queryClient,
  );
};

export type removeFavoriteResponse204 = {
  data: void;
  status: 204;
};

export type removeFavoriteResponse400 = {
  data: string;
  status: 400;
};

export type removeFavoriteResponse409 = {
  data: string;
  status: 409;
};

export type removeFavoriteResponse500 = {
  data: string;
  status: 500;
};

export type removeFavoriteResponseSuccess = removeFavoriteResponse204 & {
  headers: Headers;
};
export type removeFavoriteResponseError = (
  | removeFavoriteResponse400
  | removeFavoriteResponse409
  | removeFavoriteResponse500
) & {
  headers: Headers;
};

export type removeFavoriteResponse =
  | removeFavoriteResponseSuccess
  | removeFavoriteResponseError;

export const getRemoveFavoriteUrl = (eventId: number) => {
  return `/favorites/${eventId}`;
};

export const removeFavorite = async (
  eventId: number,
  options?: RequestInit,
): Promise<removeFavoriteResponse> => {
  return customFetch<removeFavoriteResponse>(getRemoveFavoriteUrl(eventId), {
    ...options,
    method: "DELETE",
  });
};

export const getRemoveFavoriteMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFavorite>>,
    TError,
    { eventId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeFavorite>>,
  TError,
  { eventId: number },
  TContext
> => {
  const mutationKey = ["removeFavorite"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeFavorite>>,
    { eventId: number }
  > = (props) => {
    const { eventId } = props ?? {};

    return removeFavorite(eventId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveFavoriteMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeFavorite>>
>;

export type RemoveFavoriteMutationError = string;

export const useRemoveFavorite = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeFavorite>>,
      TError,
      { eventId: number },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removeFavorite>>,
  TError,
  { eventId: number },
  TContext
> => {
  return useMutation(getRemoveFavoriteMutationOptions(options), queryClient);
};
