/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from './client';
export interface SignUpRequest {
  email?: string;
  password?: string;
}

export interface LoginRequest {
  email?: string;
  password?: string;
}

export interface LoginResponse {
  jwt?: string;
}

export interface GlobalRoleChangeRequest {
  roleId?: number;
}

export interface GlobalRoleChangeResponse {
  id?: number;
  role?: string;
  status?: string;
  requestedBy?: string;
  requestedAt?: string;
}

export interface CompanyRoleChangeRequest {
  roleId?: number;
  companyId?: number;
}

export interface CompanyRoleChangeResponse {
  id?: number;
  role?: string;
  companyId?: number;
  status?: string;
  requestedBy?: string;
  requestedAt?: string;
}

export interface CompanyCreationRequest {
  name?: string;
  payoutAccount?: string;
}

export interface CompanyCreationResponse {
  id?: number;
  name?: string;
  payoutAccount?: string;
  status?: string;
  requestedBy?: string;
  requestedAt?: string;
}

/**
 * The new status of the approval request
 */
export type ApprovalRequestReviewRequestStatus = typeof ApprovalRequestReviewRequestStatus[keyof typeof ApprovalRequestReviewRequestStatus];


export const ApprovalRequestReviewRequestStatus = {
  approved: 'approved',
  rejected: 'rejected',
} as const;

export interface ApprovalRequestReviewRequest {
  /** The new status of the approval request */
  status?: ApprovalRequestReviewRequestStatus;
}

export interface UserDto {
  id?: string;
  email?: string;
}

export interface RoleDto {
  id?: number;
  name?: string;
  description?: string;
}

export interface CompanyDto {
  id?: number;
  name?: string;
  payoutAccount?: string;
}

export type CompanyCreationRequestDtoStatus = typeof CompanyCreationRequestDtoStatus[keyof typeof CompanyCreationRequestDtoStatus];


export const CompanyCreationRequestDtoStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

export interface CompanyCreationRequestDto {
  type?: string;
  name?: string;
  payoutAccount?: string;
  id?: number;
  status?: CompanyCreationRequestDtoStatus;
  requestedBy?: string;
  requestedAt?: string;
  reviewedBy?: string;
  reviewedAt?: string;
}

export type CompanyRoleChangeRequestDtoStatus = typeof CompanyRoleChangeRequestDtoStatus[keyof typeof CompanyRoleChangeRequestDtoStatus];


export const CompanyRoleChangeRequestDtoStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

export interface CompanyRoleChangeRequestDto {
  type?: string;
  role?: string;
  company?: string;
  id?: number;
  status?: CompanyRoleChangeRequestDtoStatus;
  requestedBy?: string;
  requestedAt?: string;
  reviewedBy?: string;
  reviewedAt?: string;
}

export type GlobalRoleChangeRequestDtoStatus = typeof GlobalRoleChangeRequestDtoStatus[keyof typeof GlobalRoleChangeRequestDtoStatus];


export const GlobalRoleChangeRequestDtoStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

export interface GlobalRoleChangeRequestDto {
  type?: string;
  role?: string;
  id?: number;
  status?: GlobalRoleChangeRequestDtoStatus;
  requestedBy?: string;
  requestedAt?: string;
  reviewedBy?: string;
  reviewedAt?: string;
}

export type GetPendingApprovalRequestsParams = {
/**
 * Optional query parameter to filter approval requests by their status. If not provided, all approval requests will be returned.
 */
status?: GetPendingApprovalRequestsStatus;
};

export type GetPendingApprovalRequestsStatus = typeof GetPendingApprovalRequestsStatus[keyof typeof GetPendingApprovalRequestsStatus];


export const GetPendingApprovalRequestsStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
} as const;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type signupResponse201 = {
  data: void
  status: 201
}

export type signupResponse400 = {
  data: void
  status: 400
}

export type signupResponseSuccess = (signupResponse201) & {
  headers: Headers;
};
export type signupResponseError = (signupResponse400) & {
  headers: Headers;
};

export type signupResponse = (signupResponseSuccess | signupResponseError)

export const getSignupUrl = () => {




  return `/signup`
}

/**
 * Create a new user account with the provided email and password
 * @summary User signup
 */
export const signup = async (signUpRequest: SignUpRequest, options?: RequestInit): Promise<signupResponse> => {

  return customFetch<signupResponse>(getSignupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signUpRequest,)
  }
);}




export const getSignupMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignUpRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignUpRequest}, TContext> => {

const mutationKey = ['signup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signup>>, {data: SignUpRequest}> = (props) => {
          const {data} = props ?? {};

          return  signup(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SignupMutationResult = NonNullable<Awaited<ReturnType<typeof signup>>>
    export type SignupMutationBody = SignUpRequest
    export type SignupMutationError = void

    /**
 * @summary User signup
 */
export const useSignup = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignUpRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signup>>,
        TError,
        {data: SignUpRequest},
        TContext
      > => {
      return useMutation(getSignupMutationOptions(options), queryClient);
    }

export type loginResponse200 = {
  data: LoginResponse
  status: 200
}

export type loginResponse401 = {
  data: void
  status: 401
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse401) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `/login`
}

/**
 * Authenticate a user and return a JWT token if the credentials are valid
 * @summary User login
 */
export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginResponse> => {

  return customFetch<loginResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}




export const getLoginMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = void

    /**
 * @summary User login
 */
export const useLogin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }

export type createGlobalRoleChangeRequestResponse201 = {
  data: GlobalRoleChangeResponse
  status: 201
}

export type createGlobalRoleChangeRequestResponse400 = {
  data: void
  status: 400
}

export type createGlobalRoleChangeRequestResponseSuccess = (createGlobalRoleChangeRequestResponse201) & {
  headers: Headers;
};
export type createGlobalRoleChangeRequestResponseError = (createGlobalRoleChangeRequestResponse400) & {
  headers: Headers;
};

export type createGlobalRoleChangeRequestResponse = (createGlobalRoleChangeRequestResponseSuccess | createGlobalRoleChangeRequestResponseError)

export const getCreateGlobalRoleChangeRequestUrl = () => {




  return `/approval-requests/global-role-change`
}

/**
 * Create a new global role change approval request
 * @summary Create a global role change approval request
 */
export const createGlobalRoleChangeRequest = async (globalRoleChangeRequest: GlobalRoleChangeRequest, options?: RequestInit): Promise<createGlobalRoleChangeRequestResponse> => {

  return customFetch<createGlobalRoleChangeRequestResponse>(getCreateGlobalRoleChangeRequestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      globalRoleChangeRequest,)
  }
);}




export const getCreateGlobalRoleChangeRequestMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGlobalRoleChangeRequest>>, TError,{data: GlobalRoleChangeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createGlobalRoleChangeRequest>>, TError,{data: GlobalRoleChangeRequest}, TContext> => {

const mutationKey = ['createGlobalRoleChangeRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGlobalRoleChangeRequest>>, {data: GlobalRoleChangeRequest}> = (props) => {
          const {data} = props ?? {};

          return  createGlobalRoleChangeRequest(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateGlobalRoleChangeRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createGlobalRoleChangeRequest>>>
    export type CreateGlobalRoleChangeRequestMutationBody = GlobalRoleChangeRequest
    export type CreateGlobalRoleChangeRequestMutationError = void

    /**
 * @summary Create a global role change approval request
 */
export const useCreateGlobalRoleChangeRequest = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGlobalRoleChangeRequest>>, TError,{data: GlobalRoleChangeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGlobalRoleChangeRequest>>,
        TError,
        {data: GlobalRoleChangeRequest},
        TContext
      > => {
      return useMutation(getCreateGlobalRoleChangeRequestMutationOptions(options), queryClient);
    }

export type createCompanyRoleChangeRequestResponse201 = {
  data: CompanyRoleChangeResponse
  status: 201
}

export type createCompanyRoleChangeRequestResponse400 = {
  data: void
  status: 400
}

export type createCompanyRoleChangeRequestResponseSuccess = (createCompanyRoleChangeRequestResponse201) & {
  headers: Headers;
};
export type createCompanyRoleChangeRequestResponseError = (createCompanyRoleChangeRequestResponse400) & {
  headers: Headers;
};

export type createCompanyRoleChangeRequestResponse = (createCompanyRoleChangeRequestResponseSuccess | createCompanyRoleChangeRequestResponseError)

export const getCreateCompanyRoleChangeRequestUrl = () => {




  return `/approval-requests/company-role-change`
}

/**
 * Create a new company role change approval request
 * @summary Create a company role change approval request
 */
export const createCompanyRoleChangeRequest = async (companyRoleChangeRequest: CompanyRoleChangeRequest, options?: RequestInit): Promise<createCompanyRoleChangeRequestResponse> => {

  return customFetch<createCompanyRoleChangeRequestResponse>(getCreateCompanyRoleChangeRequestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      companyRoleChangeRequest,)
  }
);}




export const getCreateCompanyRoleChangeRequestMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCompanyRoleChangeRequest>>, TError,{data: CompanyRoleChangeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createCompanyRoleChangeRequest>>, TError,{data: CompanyRoleChangeRequest}, TContext> => {

const mutationKey = ['createCompanyRoleChangeRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCompanyRoleChangeRequest>>, {data: CompanyRoleChangeRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCompanyRoleChangeRequest(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCompanyRoleChangeRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createCompanyRoleChangeRequest>>>
    export type CreateCompanyRoleChangeRequestMutationBody = CompanyRoleChangeRequest
    export type CreateCompanyRoleChangeRequestMutationError = void

    /**
 * @summary Create a company role change approval request
 */
export const useCreateCompanyRoleChangeRequest = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCompanyRoleChangeRequest>>, TError,{data: CompanyRoleChangeRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCompanyRoleChangeRequest>>,
        TError,
        {data: CompanyRoleChangeRequest},
        TContext
      > => {
      return useMutation(getCreateCompanyRoleChangeRequestMutationOptions(options), queryClient);
    }

export type createCompanyCreationRequestResponse201 = {
  data: CompanyCreationResponse
  status: 201
}

export type createCompanyCreationRequestResponse400 = {
  data: void
  status: 400
}

export type createCompanyCreationRequestResponseSuccess = (createCompanyCreationRequestResponse201) & {
  headers: Headers;
};
export type createCompanyCreationRequestResponseError = (createCompanyCreationRequestResponse400) & {
  headers: Headers;
};

export type createCompanyCreationRequestResponse = (createCompanyCreationRequestResponseSuccess | createCompanyCreationRequestResponseError)

export const getCreateCompanyCreationRequestUrl = () => {




  return `/approval-requests/company-creation`
}

/**
 * Create a new company creation approval request
 * @summary Create a company creation approval request
 */
export const createCompanyCreationRequest = async (companyCreationRequest: CompanyCreationRequest, options?: RequestInit): Promise<createCompanyCreationRequestResponse> => {

  return customFetch<createCompanyCreationRequestResponse>(getCreateCompanyCreationRequestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      companyCreationRequest,)
  }
);}




export const getCreateCompanyCreationRequestMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCompanyCreationRequest>>, TError,{data: CompanyCreationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createCompanyCreationRequest>>, TError,{data: CompanyCreationRequest}, TContext> => {

const mutationKey = ['createCompanyCreationRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCompanyCreationRequest>>, {data: CompanyCreationRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCompanyCreationRequest(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCompanyCreationRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createCompanyCreationRequest>>>
    export type CreateCompanyCreationRequestMutationBody = CompanyCreationRequest
    export type CreateCompanyCreationRequestMutationError = void

    /**
 * @summary Create a company creation approval request
 */
export const useCreateCompanyCreationRequest = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCompanyCreationRequest>>, TError,{data: CompanyCreationRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCompanyCreationRequest>>,
        TError,
        {data: CompanyCreationRequest},
        TContext
      > => {
      return useMutation(getCreateCompanyCreationRequestMutationOptions(options), queryClient);
    }

export type deleteApprovalRequestResponse204 = {
  data: void
  status: 204
}

export type deleteApprovalRequestResponse403 = {
  data: void
  status: 403
}

export type deleteApprovalRequestResponse404 = {
  data: void
  status: 404
}

export type deleteApprovalRequestResponseSuccess = (deleteApprovalRequestResponse204) & {
  headers: Headers;
};
export type deleteApprovalRequestResponseError = (deleteApprovalRequestResponse403 | deleteApprovalRequestResponse404) & {
  headers: Headers;
};

export type deleteApprovalRequestResponse = (deleteApprovalRequestResponseSuccess | deleteApprovalRequestResponseError)

export const getDeleteApprovalRequestUrl = (id: number,) => {




  return `/approval-requests/${id}`
}

/**
 * Delete an approval request by its ID
 * @summary Delete an approval request
 */
export const deleteApprovalRequest = async (id: number, options?: RequestInit): Promise<deleteApprovalRequestResponse> => {

  return customFetch<deleteApprovalRequestResponse>(getDeleteApprovalRequestUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApprovalRequestMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApprovalRequest>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApprovalRequest>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApprovalRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApprovalRequest>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApprovalRequest(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApprovalRequestMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApprovalRequest>>>

    export type DeleteApprovalRequestMutationError = void

    /**
 * @summary Delete an approval request
 */
export const useDeleteApprovalRequest = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApprovalRequest>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApprovalRequest>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApprovalRequestMutationOptions(options), queryClient);
    }

export type reviewApprovalRequestResponse204 = {
  data: void
  status: 204
}

export type reviewApprovalRequestResponse400 = {
  data: void
  status: 400
}

export type reviewApprovalRequestResponse403 = {
  data: void
  status: 403
}

export type reviewApprovalRequestResponse404 = {
  data: void
  status: 404
}

export type reviewApprovalRequestResponseSuccess = (reviewApprovalRequestResponse204) & {
  headers: Headers;
};
export type reviewApprovalRequestResponseError = (reviewApprovalRequestResponse400 | reviewApprovalRequestResponse403 | reviewApprovalRequestResponse404) & {
  headers: Headers;
};

export type reviewApprovalRequestResponse = (reviewApprovalRequestResponseSuccess | reviewApprovalRequestResponseError)

export const getReviewApprovalRequestUrl = (id: number,) => {




  return `/approval-requests/${id}`
}

/**
 * Review an approval request by its ID, updating its status to either approved or rejected
 * @summary Review an approval request
 */
export const reviewApprovalRequest = async (id: number,
    approvalRequestReviewRequest: ApprovalRequestReviewRequest, options?: RequestInit): Promise<reviewApprovalRequestResponse> => {

  return customFetch<reviewApprovalRequestResponse>(getReviewApprovalRequestUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      approvalRequestReviewRequest,)
  }
);}




export const getReviewApprovalRequestMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reviewApprovalRequest>>, TError,{id: number;data: ApprovalRequestReviewRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reviewApprovalRequest>>, TError,{id: number;data: ApprovalRequestReviewRequest}, TContext> => {

const mutationKey = ['reviewApprovalRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reviewApprovalRequest>>, {id: number;data: ApprovalRequestReviewRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  reviewApprovalRequest(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReviewApprovalRequestMutationResult = NonNullable<Awaited<ReturnType<typeof reviewApprovalRequest>>>
    export type ReviewApprovalRequestMutationBody = ApprovalRequestReviewRequest
    export type ReviewApprovalRequestMutationError = void

    /**
 * @summary Review an approval request
 */
export const useReviewApprovalRequest = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reviewApprovalRequest>>, TError,{id: number;data: ApprovalRequestReviewRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reviewApprovalRequest>>,
        TError,
        {id: number;data: ApprovalRequestReviewRequest},
        TContext
      > => {
      return useMutation(getReviewApprovalRequestMutationOptions(options), queryClient);
    }

export type getUsersResponse200 = {
  data: UserDto[]
  status: 200
}

export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
;

export type getUsersResponse = (getUsersResponseSuccess)

export const getGetUsersUrl = () => {




  return `/users`
}

/**
 * Retrieve a list of all users
 * @summary Get users
 */
export const getUsers = async ( options?: RequestInit): Promise<getUsersResponse> => {

  return customFetch<getUsersResponse>(getGetUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersQueryKey = () => {
    return [
    `/users`
    ] as const;
    }


export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = unknown


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get users
 */

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getGlobalRolesResponse200 = {
  data: RoleDto[]
  status: 200
}

export type getGlobalRolesResponseSuccess = (getGlobalRolesResponse200) & {
  headers: Headers;
};
;

export type getGlobalRolesResponse = (getGlobalRolesResponseSuccess)

export const getGetGlobalRolesUrl = () => {




  return `/global-roles`
}

/**
 * Retrieve a list of all global roles
 * @summary Get global roles
 */
export const getGlobalRoles = async ( options?: RequestInit): Promise<getGlobalRolesResponse> => {

  return customFetch<getGlobalRolesResponse>(getGetGlobalRolesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGlobalRolesQueryKey = () => {
    return [
    `/global-roles`
    ] as const;
    }


export const getGetGlobalRolesQueryOptions = <TData = Awaited<ReturnType<typeof getGlobalRoles>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalRoles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGlobalRolesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalRoles>>> = ({ signal }) => getGlobalRoles({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGlobalRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGlobalRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getGlobalRoles>>>
export type GetGlobalRolesQueryError = unknown


export function useGetGlobalRoles<TData = Awaited<ReturnType<typeof getGlobalRoles>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalRoles>>,
          TError,
          Awaited<ReturnType<typeof getGlobalRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalRoles<TData = Awaited<ReturnType<typeof getGlobalRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGlobalRoles>>,
          TError,
          Awaited<ReturnType<typeof getGlobalRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGlobalRoles<TData = Awaited<ReturnType<typeof getGlobalRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalRoles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get global roles
 */

export function useGetGlobalRoles<TData = Awaited<ReturnType<typeof getGlobalRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGlobalRoles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGlobalRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getRolesResponse200 = {
  data: RoleDto[]
  status: 200
}

export type getRolesResponseSuccess = (getRolesResponse200) & {
  headers: Headers;
};
;

export type getRolesResponse = (getRolesResponseSuccess)

export const getGetRolesUrl = () => {




  return `/company-roles`
}

/**
 * Retrieve a list of all company roles
 * @summary Get company roles
 */
export const getRoles = async ( options?: RequestInit): Promise<getRolesResponse> => {

  return customFetch<getRolesResponse>(getGetRolesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRolesQueryKey = () => {
    return [
    `/company-roles`
    ] as const;
    }


export const getGetRolesQueryOptions = <TData = Awaited<ReturnType<typeof getRoles>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRolesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoles>>> = ({ signal }) => getRoles({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getRoles>>>
export type GetRolesQueryError = unknown


export function useGetRoles<TData = Awaited<ReturnType<typeof getRoles>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoles>>,
          TError,
          Awaited<ReturnType<typeof getRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoles<TData = Awaited<ReturnType<typeof getRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoles>>,
          TError,
          Awaited<ReturnType<typeof getRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoles<TData = Awaited<ReturnType<typeof getRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get company roles
 */

export function useGetRoles<TData = Awaited<ReturnType<typeof getRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getCompaniesResponse200 = {
  data: CompanyDto[]
  status: 200
}

export type getCompaniesResponseSuccess = (getCompaniesResponse200) & {
  headers: Headers;
};
;

export type getCompaniesResponse = (getCompaniesResponseSuccess)

export const getGetCompaniesUrl = () => {




  return `/companies`
}

/**
 * Retrieve a list of all companies
 * @summary Get all companies
 */
export const getCompanies = async ( options?: RequestInit): Promise<getCompaniesResponse> => {

  return customFetch<getCompaniesResponse>(getGetCompaniesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCompaniesQueryKey = () => {
    return [
    `/companies`
    ] as const;
    }


export const getGetCompaniesQueryOptions = <TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompaniesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompanies>>> = ({ signal }) => getCompanies({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompaniesQueryResult = NonNullable<Awaited<ReturnType<typeof getCompanies>>>
export type GetCompaniesQueryError = unknown


export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanies>>,
          TError,
          Awaited<ReturnType<typeof getCompanies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanies>>,
          TError,
          Awaited<ReturnType<typeof getCompanies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all companies
 */

export function useGetCompanies<TData = Awaited<ReturnType<typeof getCompanies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanies>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompaniesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getPendingApprovalRequestsResponse200 = {
  data: string[]
  status: 200
}

export type getPendingApprovalRequestsResponse403 = {
  data: void
  status: 403
}

export type getPendingApprovalRequestsResponseSuccess = (getPendingApprovalRequestsResponse200) & {
  headers: Headers;
};
export type getPendingApprovalRequestsResponseError = (getPendingApprovalRequestsResponse403) & {
  headers: Headers;
};

export type getPendingApprovalRequestsResponse = (getPendingApprovalRequestsResponseSuccess | getPendingApprovalRequestsResponseError)

export const getGetPendingApprovalRequestsUrl = (params?: GetPendingApprovalRequestsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/approval-requests?${stringifiedParams}` : `/approval-requests`
}

/**
 * Get all approval requests, or filter by status
 * @summary Get approval requests
 */
export const getPendingApprovalRequests = async (params?: GetPendingApprovalRequestsParams, options?: RequestInit): Promise<getPendingApprovalRequestsResponse> => {

  return customFetch<getPendingApprovalRequestsResponse>(getGetPendingApprovalRequestsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPendingApprovalRequestsQueryKey = (params?: GetPendingApprovalRequestsParams,) => {
    return [
    `/approval-requests`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPendingApprovalRequestsQueryOptions = <TData = Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError = void>(params?: GetPendingApprovalRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPendingApprovalRequestsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPendingApprovalRequests>>> = ({ signal }) => getPendingApprovalRequests(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPendingApprovalRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof getPendingApprovalRequests>>>
export type GetPendingApprovalRequestsQueryError = void


export function useGetPendingApprovalRequests<TData = Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError = void>(
 params: undefined |  GetPendingApprovalRequestsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPendingApprovalRequests>>,
          TError,
          Awaited<ReturnType<typeof getPendingApprovalRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPendingApprovalRequests<TData = Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError = void>(
 params?: GetPendingApprovalRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPendingApprovalRequests>>,
          TError,
          Awaited<ReturnType<typeof getPendingApprovalRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPendingApprovalRequests<TData = Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError = void>(
 params?: GetPendingApprovalRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get approval requests
 */

export function useGetPendingApprovalRequests<TData = Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError = void>(
 params?: GetPendingApprovalRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingApprovalRequests>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPendingApprovalRequestsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type deleteUserResponse204 = {
  data: void
  status: 204
}

export type deleteUserResponse403 = {
  data: void
  status: 403
}

export type deleteUserResponse404 = {
  data: void
  status: 404
}

export type deleteUserResponseSuccess = (deleteUserResponse204) & {
  headers: Headers;
};
export type deleteUserResponseError = (deleteUserResponse403 | deleteUserResponse404) & {
  headers: Headers;
};

export type deleteUserResponse = (deleteUserResponseSuccess | deleteUserResponseError)

export const getDeleteUserUrl = (id: string,) => {




  return `/users/${id}`
}

/**
 * Delete a user by their ID
 * @summary Delete user
 */
export const deleteUser = async (id: string, options?: RequestInit): Promise<deleteUserResponse> => {

  return customFetch<deleteUserResponse>(getDeleteUserUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteUser(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>

    export type DeleteUserMutationError = void

    /**
 * @summary Delete user
 */
export const useDeleteUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteUserMutationOptions(options), queryClient);
    }

export type deleteAccountResponse200 = {
  data: void
  status: 200
}

export type deleteAccountResponseSuccess = (deleteAccountResponse200) & {
  headers: Headers;
};
;

export type deleteAccountResponse = (deleteAccountResponseSuccess)

export const getDeleteAccountUrl = () => {




  return `/me`
}

/**
 * Delete the authenticated user's account
 * @summary Delete user account
 */
export const deleteAccount = async ( options?: RequestInit): Promise<deleteAccountResponse> => {

  return customFetch<deleteAccountResponse>(getDeleteAccountUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAccountMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAccount>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAccount>>, TError,void, TContext> => {

const mutationKey = ['deleteAccount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAccount>>, void> = () => {


          return  deleteAccount(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAccountMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAccount>>>

    export type DeleteAccountMutationError = unknown

    /**
 * @summary Delete user account
 */
export const useDeleteAccount = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAccount>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAccount>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteAccountMutationOptions(options), queryClient);
    }

export type deleteCompanyResponse204 = {
  data: void
  status: 204
}

export type deleteCompanyResponse403 = {
  data: void
  status: 403
}

export type deleteCompanyResponse404 = {
  data: void
  status: 404
}

export type deleteCompanyResponseSuccess = (deleteCompanyResponse204) & {
  headers: Headers;
};
export type deleteCompanyResponseError = (deleteCompanyResponse403 | deleteCompanyResponse404) & {
  headers: Headers;
};

export type deleteCompanyResponse = (deleteCompanyResponseSuccess | deleteCompanyResponseError)

export const getDeleteCompanyUrl = (id: number,) => {




  return `/companies/${id}`
}

/**
 * Delete a company by its ID. Only users with ADMIN authority or ADMIN authority for the specific company can perform this action.
 * @summary Delete a company
 */
export const deleteCompany = async (id: number, options?: RequestInit): Promise<deleteCompanyResponse> => {

  return customFetch<deleteCompanyResponse>(getDeleteCompanyUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteCompanyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompany>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCompany>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCompany'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCompany>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCompany(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCompany>>>

    export type DeleteCompanyMutationError = void

    /**
 * @summary Delete a company
 */
export const useDeleteCompany = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompany>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCompany>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCompanyMutationOptions(options), queryClient);
    }
