/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetchOrderApi } from "./client";
export interface OrderItemRequest {
  ticketListingId?: number;
  quantity?: number;
}

export interface CreateOrderRequest {
  items?: OrderItemRequest[];
}

export interface OrderItemResponse {
  orderItemId?: number;
  ticketListingId?: number;
  quantity?: number;
  unitPrice?: number;
  lineTotal?: number;
}

export interface OrderResponse {
  orderId?: string;
  orderNumber?: string;
  userId?: string;
  totalAmount?: number;
  currency?: string;
  paymentStatus?: string;
  orderStatus?: string;
  createdAt?: string;
  expiresAt?: string;
  items?: OrderItemResponse[];
}

export interface ProcessPaymentRequest {
  forceFailure?: boolean;
}

export interface PaymentResponse {
  paymentId?: string;
  orderId?: string;
  paymentProvider?: string;
  providerPaymentId?: string;
  amount?: number;
  currency?: string;
  status?: string;
  createdAt?: string;
}

export interface PayoutResponse {
  payoutId?: number;
  companyId?: number;
  payoutAmount?: number;
  currency?: string;
  payoutStatus?: string;
  payoutReference?: string;
  createdAt?: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type createOrderResponse200 = {
  data: OrderResponse;
  status: 200;
};

export type createOrderResponse400 = {
  data: string;
  status: 400;
};

export type createOrderResponse401 = {
  data: string;
  status: 401;
};

export type createOrderResponse403 = {
  data: string;
  status: 403;
};

export type createOrderResponse404 = {
  data: string;
  status: 404;
};

export type createOrderResponse409 = {
  data: string;
  status: 409;
};

export type createOrderResponse500 = {
  data: string;
  status: 500;
};

export type createOrderResponse502 = {
  data: string;
  status: 502;
};

export type createOrderResponseSuccess = createOrderResponse200 & {
  headers: Headers;
};
export type createOrderResponseError = (
  | createOrderResponse400
  | createOrderResponse401
  | createOrderResponse403
  | createOrderResponse404
  | createOrderResponse409
  | createOrderResponse500
  | createOrderResponse502
) & {
  headers: Headers;
};

export type createOrderResponse =
  | createOrderResponseSuccess
  | createOrderResponseError;

export const getCreateOrderUrl = () => {
  return `/orders`;
};

export const createOrder = async (
  createOrderRequest: CreateOrderRequest,
  options?: RequestInit,
): Promise<createOrderResponse> => {
  return customFetchOrderApi<createOrderResponse>(getCreateOrderUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createOrderRequest),
  });
};

export const getCreateOrderMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOrder>>,
    TError,
    { data: CreateOrderRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetchOrderApi>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOrder>>,
  TError,
  { data: CreateOrderRequest },
  TContext
> => {
  const mutationKey = ["createOrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOrder>>,
    { data: CreateOrderRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createOrder(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOrder>>
>;
export type CreateOrderMutationBody = CreateOrderRequest;
export type CreateOrderMutationError = string;

export const useCreateOrder = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createOrder>>,
      TError,
      { data: CreateOrderRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createOrder>>,
  TError,
  { data: CreateOrderRequest },
  TContext
> => {
  return useMutation(getCreateOrderMutationOptions(options), queryClient);
};

export type payOrderResponse200 = {
  data: PaymentResponse;
  status: 200;
};

export type payOrderResponse400 = {
  data: string;
  status: 400;
};

export type payOrderResponse401 = {
  data: string;
  status: 401;
};

export type payOrderResponse403 = {
  data: string;
  status: 403;
};

export type payOrderResponse404 = {
  data: string;
  status: 404;
};

export type payOrderResponse409 = {
  data: string;
  status: 409;
};

export type payOrderResponse500 = {
  data: string;
  status: 500;
};

export type payOrderResponse502 = {
  data: string;
  status: 502;
};

export type payOrderResponseSuccess = payOrderResponse200 & {
  headers: Headers;
};
export type payOrderResponseError = (
  | payOrderResponse400
  | payOrderResponse401
  | payOrderResponse403
  | payOrderResponse404
  | payOrderResponse409
  | payOrderResponse500
  | payOrderResponse502
) & {
  headers: Headers;
};

export type payOrderResponse = payOrderResponseSuccess | payOrderResponseError;

export const getPayOrderUrl = (id: string) => {
  return `/orders/${id}/pay`;
};

export const payOrder = async (
  id: string,
  processPaymentRequest?: ProcessPaymentRequest,
  options?: RequestInit,
): Promise<payOrderResponse> => {
  return customFetchOrderApi<payOrderResponse>(getPayOrderUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(processPaymentRequest),
  });
};

export const getPayOrderMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof payOrder>>,
    TError,
    { id: string; data?: ProcessPaymentRequest },
    TContext
  >;
  request?: SecondParameter<typeof customFetchOrderApi>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof payOrder>>,
  TError,
  { id: string; data?: ProcessPaymentRequest },
  TContext
> => {
  const mutationKey = ["payOrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof payOrder>>,
    { id: string; data?: ProcessPaymentRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return payOrder(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PayOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof payOrder>>
>;
export type PayOrderMutationBody = ProcessPaymentRequest | undefined;
export type PayOrderMutationError = string;

export const usePayOrder = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof payOrder>>,
      TError,
      { id: string; data?: ProcessPaymentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof payOrder>>,
  TError,
  { id: string; data?: ProcessPaymentRequest },
  TContext
> => {
  return useMutation(getPayOrderMutationOptions(options), queryClient);
};

export type getMyPayoutsResponse200 = {
  data: PayoutResponse[];
  status: 200;
};

export type getMyPayoutsResponse400 = {
  data: string;
  status: 400;
};

export type getMyPayoutsResponse401 = {
  data: string;
  status: 401;
};

export type getMyPayoutsResponse403 = {
  data: string;
  status: 403;
};

export type getMyPayoutsResponse404 = {
  data: string;
  status: 404;
};

export type getMyPayoutsResponse409 = {
  data: string;
  status: 409;
};

export type getMyPayoutsResponse500 = {
  data: string;
  status: 500;
};

export type getMyPayoutsResponse502 = {
  data: string;
  status: 502;
};

export type getMyPayoutsResponseSuccess = getMyPayoutsResponse200 & {
  headers: Headers;
};
export type getMyPayoutsResponseError = (
  | getMyPayoutsResponse400
  | getMyPayoutsResponse401
  | getMyPayoutsResponse403
  | getMyPayoutsResponse404
  | getMyPayoutsResponse409
  | getMyPayoutsResponse500
  | getMyPayoutsResponse502
) & {
  headers: Headers;
};

export type getMyPayoutsResponse =
  | getMyPayoutsResponseSuccess
  | getMyPayoutsResponseError;

export const getGetMyPayoutsUrl = () => {
  return `/payouts`;
};

export const getMyPayouts = async (
  options?: RequestInit,
): Promise<getMyPayoutsResponse> => {
  return customFetchOrderApi<getMyPayoutsResponse>(getGetMyPayoutsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyPayoutsQueryKey = () => {
  return [`/payouts`] as const;
};

export const getGetMyPayoutsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyPayouts>>,
  TError = string,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMyPayouts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetchOrderApi>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyPayoutsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyPayouts>>> = ({
    signal,
  }) => getMyPayouts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyPayouts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyPayoutsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyPayouts>>
>;
export type GetMyPayoutsQueryError = string;

export function useGetMyPayouts<
  TData = Awaited<ReturnType<typeof getMyPayouts>>,
  TError = string,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyPayouts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPayouts>>,
          TError,
          Awaited<ReturnType<typeof getMyPayouts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPayouts<
  TData = Awaited<ReturnType<typeof getMyPayouts>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyPayouts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPayouts>>,
          TError,
          Awaited<ReturnType<typeof getMyPayouts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPayouts<
  TData = Awaited<ReturnType<typeof getMyPayouts>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyPayouts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetMyPayouts<
  TData = Awaited<ReturnType<typeof getMyPayouts>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyPayouts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyPayoutsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getOrderResponse200 = {
  data: OrderResponse;
  status: 200;
};

export type getOrderResponse400 = {
  data: string;
  status: 400;
};

export type getOrderResponse401 = {
  data: string;
  status: 401;
};

export type getOrderResponse403 = {
  data: string;
  status: 403;
};

export type getOrderResponse404 = {
  data: string;
  status: 404;
};

export type getOrderResponse409 = {
  data: string;
  status: 409;
};

export type getOrderResponse500 = {
  data: string;
  status: 500;
};

export type getOrderResponse502 = {
  data: string;
  status: 502;
};

export type getOrderResponseSuccess = getOrderResponse200 & {
  headers: Headers;
};
export type getOrderResponseError = (
  | getOrderResponse400
  | getOrderResponse401
  | getOrderResponse403
  | getOrderResponse404
  | getOrderResponse409
  | getOrderResponse500
  | getOrderResponse502
) & {
  headers: Headers;
};

export type getOrderResponse = getOrderResponseSuccess | getOrderResponseError;

export const getGetOrderUrl = (id: string) => {
  return `/orders/${id}`;
};

export const getOrder = async (
  id: string,
  options?: RequestInit,
): Promise<getOrderResponse> => {
  return customFetchOrderApi<getOrderResponse>(getGetOrderUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetOrderQueryKey = (id: string) => {
  return [`/orders/${id}`] as const;
};

export const getGetOrderQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrder>>,
  TError = string,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOrderQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrder>>> = ({
    signal,
  }) => getOrder(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetOrderQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrder>>
>;
export type GetOrderQueryError = string;

export function useGetOrder<
  TData = Awaited<ReturnType<typeof getOrder>>,
  TError = string,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrder>>,
          TError,
          Awaited<ReturnType<typeof getOrder>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrder<
  TData = Awaited<ReturnType<typeof getOrder>>,
  TError = string,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrder>>,
          TError,
          Awaited<ReturnType<typeof getOrder>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrder<
  TData = Awaited<ReturnType<typeof getOrder>>,
  TError = string,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetOrder<
  TData = Awaited<ReturnType<typeof getOrder>>,
  TError = string,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOrderQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type cancelOrderResponse200 = {
  data: OrderResponse;
  status: 200;
};

export type cancelOrderResponse400 = {
  data: string;
  status: 400;
};

export type cancelOrderResponse401 = {
  data: string;
  status: 401;
};

export type cancelOrderResponse403 = {
  data: string;
  status: 403;
};

export type cancelOrderResponse404 = {
  data: string;
  status: 404;
};

export type cancelOrderResponse409 = {
  data: string;
  status: 409;
};

export type cancelOrderResponse500 = {
  data: string;
  status: 500;
};

export type cancelOrderResponse502 = {
  data: string;
  status: 502;
};

export type cancelOrderResponseSuccess = cancelOrderResponse200 & {
  headers: Headers;
};
export type cancelOrderResponseError = (
  | cancelOrderResponse400
  | cancelOrderResponse401
  | cancelOrderResponse403
  | cancelOrderResponse404
  | cancelOrderResponse409
  | cancelOrderResponse500
  | cancelOrderResponse502
) & {
  headers: Headers;
};

export type cancelOrderResponse =
  | cancelOrderResponseSuccess
  | cancelOrderResponseError;

export const getCancelOrderUrl = (id: string) => {
  return `/orders/${id}`;
};

export const cancelOrder = async (
  id: string,
  options?: RequestInit,
): Promise<cancelOrderResponse> => {
  return customFetchOrderApi<cancelOrderResponse>(getCancelOrderUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getCancelOrderMutationOptions = <
  TError = string,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelOrder>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetchOrderApi>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelOrder>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["cancelOrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelOrder>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return cancelOrder(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelOrder>>
>;

export type CancelOrderMutationError = string;

export const useCancelOrder = <TError = string, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelOrder>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelOrder>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getCancelOrderMutationOptions(options), queryClient);
};

export type getMyOrdersResponse200 = {
  data: OrderResponse[];
  status: 200;
};

export type getMyOrdersResponse400 = {
  data: string;
  status: 400;
};

export type getMyOrdersResponse401 = {
  data: string;
  status: 401;
};

export type getMyOrdersResponse403 = {
  data: string;
  status: 403;
};

export type getMyOrdersResponse404 = {
  data: string;
  status: 404;
};

export type getMyOrdersResponse409 = {
  data: string;
  status: 409;
};

export type getMyOrdersResponse500 = {
  data: string;
  status: 500;
};

export type getMyOrdersResponse502 = {
  data: string;
  status: 502;
};

export type getMyOrdersResponseSuccess = getMyOrdersResponse200 & {
  headers: Headers;
};
export type getMyOrdersResponseError = (
  | getMyOrdersResponse400
  | getMyOrdersResponse401
  | getMyOrdersResponse403
  | getMyOrdersResponse404
  | getMyOrdersResponse409
  | getMyOrdersResponse500
  | getMyOrdersResponse502
) & {
  headers: Headers;
};

export type getMyOrdersResponse =
  | getMyOrdersResponseSuccess
  | getMyOrdersResponseError;

export const getGetMyOrdersUrl = () => {
  return `/orders/me`;
};

export const getMyOrders = async (
  options?: RequestInit,
): Promise<getMyOrdersResponse> => {
  return customFetchOrderApi<getMyOrdersResponse>(getGetMyOrdersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyOrdersQueryKey = () => {
  return [`/orders/me`] as const;
};

export const getGetMyOrdersQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyOrders>>,
  TError = string,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMyOrders>>, TError, TData>
  >;
  request?: SecondParameter<typeof customFetchOrderApi>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyOrdersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyOrders>>> = ({
    signal,
  }) => getMyOrders({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyOrders>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyOrdersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyOrders>>
>;
export type GetMyOrdersQueryError = string;

export function useGetMyOrders<
  TData = Awaited<ReturnType<typeof getMyOrders>>,
  TError = string,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyOrders>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyOrders>>,
          TError,
          Awaited<ReturnType<typeof getMyOrders>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyOrders<
  TData = Awaited<ReturnType<typeof getMyOrders>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyOrders>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyOrders>>,
          TError,
          Awaited<ReturnType<typeof getMyOrders>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyOrders<
  TData = Awaited<ReturnType<typeof getMyOrders>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyOrders>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetMyOrders<
  TData = Awaited<ReturnType<typeof getMyOrders>>,
  TError = string,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyOrders>>, TError, TData>
    >;
    request?: SecondParameter<typeof customFetchOrderApi>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyOrdersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
